name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
    - pipeline: build_pipeline
      source: "Prescriptions-For-Patients-Build"
      trigger:
        branches:
          include:
            - refs/tags/v*

pool:
  name: "AWS-ECS"

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    jinja_templates:
      ALLOW_NHS_NUMBER_OVERRIDE: false
    prod_producer_approval: true
    manual_approval_env: prescriptions-for-patients
    apigee_deployments:
      - environment: manual-approval
        stage_name: qa_manual_approval
      - environment: manual-approval
        stage_name: ref_manual_approval
      - environment: manual-approval
        stage_name: int_manual_approval
      - environment: internal-dev
        post_deploy:
          - template: ./templates/post_dev_deploy.yml
        jinja_templates:
          ALLOW_NHS_NUMBER_OVERRIDE: true
          TARGET_SERVER: prescriptions-for-patients-eps
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        post_deploy:
          - template: ./templates/run_tests.yml
        jinja_templates:
          ALLOW_NHS_NUMBER_OVERRIDE: false
      - environment: internal-qa
        post_deploy:
          - template: ./templates/run_tests.yml
            parameters:
              full: true
        depends_on:
          - internal_dev
          - qa_manual_approval
        jinja_templates:
          ALLOW_NHS_NUMBER_OVERRIDE: true
          TARGET_SERVER: prescriptions-for-patients
      - environment: ref
        post_deploy:
          - template: ./templates/run_tests.yml
        depends_on:
          - internal_dev
          - ref_manual_approval
        jinja_templates:
          ALLOW_NHS_NUMBER_OVERRIDE: true
          TARGET_SERVER: prescriptions-for-patients-eps
      - environment: sandbox
        proxy_path: sandbox
        depends_on:
          - internal_qa
          - int_manual_approval
        jinja_templates:
          ALLOW_NHS_NUMBER_OVERRIDE: false
      - environment: int
        pre_deploy:
          - template: ./templates/pre_int_deploy.yml
        post_deploy:
          - template: ./templates/post_int_deploy.yml
        depends_on:
          - internal_qa
          - int_manual_approval
        jinja_templates:
          ALLOW_NHS_NUMBER_OVERRIDE: true
          TARGET_SERVER: prescriptions-for-patients
      - environment: prod
        post_deploy:
          - template: ./templates/post_prod_deploy.yml
        depends_on:
          - sandbox
          - int
        jinja_templates:
          ALLOW_NHS_NUMBER_OVERRIDE: false
          TARGET_SERVER: prescriptions-for-patients
