name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Prescriptions-For-Patients-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }} 
    short_service_name: ${{ variables.short_service_name }} 
    service_base_path: ${{ variables.service_base_path }} 
    jinja_templates:
      ALLOW_NHS_NUMBER_OVERRIDE: false
    apigee_deployments:
      - environment: internal-dev
        pre_deploy:
          - template: ./templates/post_dev_deploy.yml
        post_deploy:
          - template: ./templates/post_int_deploy.yml
        jinja_templates:
          ALLOW_NHS_NUMBER_OVERRIDE: true
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        pre_deploy:
          - template: ./templates/post_prod_deploy.yml
        post_deploy:
          - template: ./templates/pre_int_deploy.yml
